import voiceThumbnailPath from '../../assets/images/voice-thumbnail.jpg'

export const VoiceData = [
  {
    id: 1,
    thumbnailPath: voiceThumbnailPath,
    alt: '山田太郎の画像',
    title: 'インターンで人生が変わりましたあああああああ。',
    university_and_name: '上智大学4年 | 中澤さん',
    href: '/nakazawa',
  },
  {
    id: 2,
    thumbnailPath: voiceThumbnailPath,
    alt: '山田太郎の画像',
    title: 'インターンで人生が変わりましたあああああああ。',
    university_and_name: '上智大学4年 | 中澤さん',
    href: '/nakazawa',
  },
  {
    id: 3,
    thumbnailPath: voiceThumbnailPath,
    alt: '山田太郎の画像',
    title: 'インターンで人生が変わりましたあああああああ。',
    university_and_name: '上智大学4年 | 中澤さん',
    href: '/nakazawa',
  },
  {
    id: 4,
    thumbnailPath: voiceThumbnailPath,
    alt: '山田太郎の画像',
    title: 'インターンで人生が変わりましたあああああああ。',
    university_and_name: '上智大学4年 | 中澤さん',
    href: '/nakazawa',
  },
  {
    id: 5,
    thumbnailPath: voiceThumbnailPath,
    alt: '山田太郎の画像',
    title: 'インターンで人生が変わりましたあああああああ。',
    university_and_name: '上智大学4年 | 中澤さん',
    href: '/nakazawa',
  },
  {
    id: 6,
    thumbnailPath: voiceThumbnailPath,
    alt: '山田太郎の画像',
    title: 'インターンで人生が変わりましたあああああああ。',
    university_and_name: '上智大学4年 | 中澤さん',
    href: '/nakazawa',
  },
  {
    id: 7,
    thumbnailPath: voiceThumbnailPath,
    alt: '山田太郎の画像',
    title: 'インターンで人生が変わりましたあああああああ。',
    university_and_name: '上智大学4年 | 中澤さん',
    href: '/nakazawa',
  },
  {
    id: 8,
    thumbnailPath: voiceThumbnailPath,
    alt: '山田太郎の画像',
    title: 'インターンで人生が変わりましたあああああああ。',
    university_and_name: '上智大学4年 | 中澤さん',
    href: '/nakazawa',
  },
  {
    id: 9,
    thumbnailPath: voiceThumbnailPath,
    alt: '山田太郎の画像',
    title: 'インターンで人生が変わりましたあああああああ。',
    university_and_name: '上智大学4年 | 中澤さん',
    href: '/nakazawa',
  },
]
